version: '3.9'

services:
  hit_counter:
    image: hitcounter_v2
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: pass123
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  mongo: 
    image: mongo 
    restart: always 
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass123
      # MONGO_INITDB_DATABASE: hitcounter_db
    # volumes:
    #   - hitcounter_mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass123@mongo:27017/  

# volumes:
#   hitcounter_mongodb:
